version: '3.8'

services:
  fluentd:
    image: fluent/fluentd:v1.16-1
    container_name: fluentd
    volumes:
      # Mount the configuration file into the container
      - ./fluentd/conf:/fluentd/etc
    ports:
      # This is the port your services will send logs to
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - logging-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Adjust memory for local dev
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - logging-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.2
    container_name: kibana
    ports:
      # Access Kibana UI at http://localhost:5601
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - logging-net

networks:
  logging-net:
    driver: bridge