services:
  zookeeper:
    build: ./zookeeper
    platform: linux/arm64
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_4LW_COMMANDS_WHITELIST=*
    networks:
      - logging-net
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  kafka:
    image: bitnami/kafka:latest
    platform: linux/arm64
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - logging-net
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    platform: linux/arm64
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - logging-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  fluentd:
    build: ./fluentd
    platform: linux/arm64
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24225:24225"
      - "24225:24225/udp"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - logging-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:24226/api/plugins.json || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.2
    platform: linux/arm64
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - logging-net

  ingestion-service:
    build:
      context: .
      dockerfile: ./services/ingestion/Dockerfile
    platform: linux/arm64
    container_name: ingestion-service
    environment:
      - SERVICE_NAME=ingestion
    logging:
      driver: "fluentd"
      options:
        fluentd-address: fluentd:24225
        tag: service.ingestion
        fluentd-retry-wait: "1s"
        fluentd-max-retries: "30"
    depends_on:
      kafka:
        condition: service_healthy
      fluentd:
        condition: service_healthy
    networks:
      - logging-net
    restart: on-failure

networks:
  logging-net:
    driver: bridge